# My Solution for H0

In [1]:
import pandas as pd
import numpy as np

In [51]:
dict = {"a": [1, 4, 7], "b": [2, 5, 8], "c": [3, 6, 9]}
df = pd.DataFrame(dict)

np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(df)
print(np_array)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [53]:
# initalize
dict = {"a": [1, 4, 7], "b": [2, 5, 8], "c": [3, 6, 9]}
df = pd.DataFrame(dict)
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# sum accross rows axis=0
print(df.sum(axis=0))

# sum accross rows
print(np.sum(np_array, axis=0))

a    12
b    15
c    18
dtype: int64
[12 15 18]


In [54]:
# initalize
dict = {"a": [1, 4, 7], "b": [2, 5, 8], "c": [3, 6, 9]}
df = pd.DataFrame(dict)
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# sum accross columns axis=1
print(df.sum(axis=1))

# sum accross columns axis=1
print(np.sum(np_array, axis=1))

0     6
1    15
2    24
dtype: int64
[ 6 15 24]


In [56]:
# initalize
dict = {"a": [1, 4, 7], "b": [2, 5, 8], "c": [3, 6, 9]}
df = pd.DataFrame(dict)
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# reshaping
ar = np.array([1, 2, 3,4,5,6])
ar = ar.reshape((2,3))
print(ar)

# indexing
print(np.indices(ar.shape))
print(ar[:,[0,2]])

[[1 2 3]
 [4 5 6]]
[[[0 0 0]
  [1 1 1]]

 [[0 1 2]
  [0 1 2]]]
[[1 3]
 [4 6]]


## np.array to df

In [91]:
# initialize
ar = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(ar)

df = pd.DataFrame(ar, columns=["a", "b", "c"], index=["x", "y", "z"])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   a  b  c
x  1  2  3
y  4  5  6
z  7  8  9


In [95]:
print(df.loc["x", "a"])
print(df.loc["x", ["a","c"]])
print(type(df.loc["x", ["a","c"]]))
print(df.loc["x", ["a","c"]] + 1)
print(df==2)

1
a    1
c    3
Name: x, dtype: int64
<class 'pandas.core.series.Series'>
a    2
c    4
Name: x, dtype: int64
       a      b      c
x  False   True  False
y  False  False  False
z  False  False  False


### Actual HW

In [106]:
import os
path = os.path.join(os.getcwd(), "data")
df = pd.read_csv(f"{path}/interactive_data.csv")
df

Unnamed: 0         Intent         Gender            Age  \
0             1  None selected  None selected  None selected   
1             2  None selected  None selected  None selected   
2             3  None selected  None selected  None selected   
3             4  None selected  None selected  None selected   
4             5  None selected  None selected  None selected   
..          ...            ...            ...            ...   
535         536        Unknown           Male              5   
536         537        Unknown           Male              5   
537         538        Unknown           Male              5   
538         539        Unknown           Male              5   
539         540        Unknown           Male              5   

                       Race  Deaths  Population  Rate  
0             None selected   33599   316299978  10.6  
1                     White   22079   197369634  11.2  
2                     Black    7765    38896382  20.0  
3                  Hispanic    3007    54049078   5.6  
4    Asian/Pacific Islander     442    16315561   2.7  
..                      ...     ...         ...   ...  
535                   White       0           0   NaN  
536                   Black       0           0   NaN  
537                Hispanic       0           0   NaN  
538  Asian/Pacific Islander       0           0   NaN  
539                   Other       0           0   NaN  

[540 rows x 8 columns]

In [111]:
# filter
df_filtered = df.loc[~(df=='None selected').any(axis=1)]
df_filtered

Unnamed: 0   Intent  Gender       Age                    Race  Deaths  \
151         152  Suicide  Female  Under 15                   White      19   
152         153  Suicide  Female  Under 15                   Black       1   
153         154  Suicide  Female  Under 15                Hispanic       4   
154         155  Suicide  Female  Under 15  Asian/Pacific Islander       1   
155         156  Suicide  Female  Under 15                   Other       0   
..          ...      ...     ...       ...                     ...     ...   
535         536  Unknown    Male         5                   White       0   
536         537  Unknown    Male         5                   Black       0   
537         538  Unknown    Male         5                Hispanic       0   
538         539  Unknown    Male         5  Asian/Pacific Islander       0   
539         540  Unknown    Male         5                   Other       0   

     Population  Rate  
151    15355910   0.1  
152     4095428   0.0  
153     7330024   0.1  
154     1393440   0.1  
155     1661877   0.0  
..          ...   ...  
535           0   NaN  
536           0   NaN  
537           0   NaN  
538           0   NaN  
539           0   NaN  

[200 rows x 8 columns]

In [155]:
df_filtered['Age'].unique()

array(['Under 15', '15 - 34', '35 - 64', '65+', '5'], dtype=object)

In [170]:
# results
all_deaths = df_filtered.sum(axis=0)['Deaths']

df_suicides = df_filtered.loc[(df_filtered=='Suicide').any(axis='columns')]
suicides = df_suicides.sum(axis='index')['Deaths']
print(f"Percentage of suicides: {100*suicides / all_deaths}%")

males = df_filtered.loc[(df_filtered=='Male').any(axis='columns')].sum(axis='index')['Deaths']
male_suicides = df_suicides.loc[(df_suicides=='Male').Gender].sum(axis='index')['Deaths']
print(f"Percentage of male suicides: {100*male_suicides / suicides}%")

df_homicides = df_filtered.loc[(df_filtered=='Homicide').Intent]
homicides = df_homicides.sum(axis=0).Deaths
print(f"Percentage of homicides: {(100 * homicides / all_deaths)}%")

df_homicides_male_between_15_and_34 = df_homicides.loc[(df_homicides['Gender']=='Male')
                                                       & (df_homicides['Age']=='15 - 34')]
homicides_male_between_15_and_34 = df_homicides_male_between_15_and_34.sum(axis=0).Deaths
df_black_male_homicides_between_15_and_34 = df_homicides.loc[(df_homicides['Gender']=='Male')
                                                            & (df_homicides['Race']=='Black')
                                                            & (df_homicides['Age']=='15 - 34')]
black_male_homicide_between_15_and_34 = df_black_male_homicides_between_15_and_34.Deaths.sum(axis=0)

print(f"Percentage of males homicides with black colour between 15 and 34: {100 * black_male_homicide_between_15_and_34 / homicides_male_between_15_and_34}%")

female_homicides = df_filtered.loc[(df_filtered.Gender=='Female')
                               & (df_filtered.Intent=='Homicide')].Deaths.sum(axis=0)
print(f"Percentage of female homicides {100 * female_homicides / homicides}%")

females = df_filtered.loc[(df_filtered=='Female').any(axis='columns')].sum(axis='index')['Deaths']

Percentage of suicides: 62.68194671826165%
Percentage of male suicides: 86.24275809668535%
Percentage of homicides: 34.906980205387704%
Percentage of males homicides with black colour between 15 and 34: 66.12482748044778%
Percentage of female homicides 15.28950285665558%
